version: '3.8'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Ngochuy123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql:/var/opt/mssql

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:8080"  
      - "5001:8081"  

    depends_on:
      - sql
    networks:
      - app-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    networks:
      - app-network
  
  nginx-app:
    build: ./nginx
    ports:
      - "8010:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mssql: